amane-s.txt
=> add amane-s.txt

2B.txt
自分用のテキストファイルを追加しました！
問題がなければマージお願いします！
=> add 2B.txt

suzuki2.txt, szk-23.txt
ブランチを切ってすぐにコミット、プッシュしたらボタン表示されました。
さきほどは何度かプッシュしていました。
丁寧な対応ありがとうございました。
=> Check button

README.md
READMEに「Compare & pull request」のボタンが見当たらない場合の対応を追記しました
=> add 「Compare & pull request」のボタンが見当たらない場合

yongsoo.txt
Hello, I am reading this book in korea and submitting pull request here!
=> add my greetings here.

aaea.txt
=> add aaea.txt

MizukoA.txt
GitとGitHubとSourceTreeの練習です！
よろしくお願いします♡
=> add MizukoA.txt

sha.txt
=> add aha.txt

.gitignore, 2B.txt, wakawaka.txt, wakawaka2.txt
テキストファイル「wakawaka.txt」を作成しました。
=> add wakawaka.txt

wakawaka2.txt
Rervertトとプルリクエストのテストです
This reverts commit 77c631bf4bf72a6f311daa51e23bfef85eb85fac.
=> Revert "add wakawaka2.txt"

.gitignore, wakawaka2.txt
=> add-fileブランチ→masterブランチヘマージ、プルリクエスト

ndMasaki.txt
=> add ndMasaki.txt

apfel0.txt
=> add apfel0.txt

kampei-mk.txt
テキスト記載（pp.153-154）に基づき、Pull Requestの練習を行います。
テキストファイルの新規追加
=> Pullreq test

teikouFile.txt
=> add teikouFile.txt

ukkynal3.txt
=> Puerto Rico

T-Ig.txt
自分用のTESTファイルを追加した。
初回　add-myfile ブランチのままだとPush出来なかった?
=> Add T-Ig.txt

T-Ig2nd.txt, T-Ig3rd.txt
メールでの返信、ありがとうございます。
プッシュするときに、リモートリポジトリをデフォルトになっている add-myfile で実行すると、
ブラウザ表示しているリモート(elmas3からForkした 自アカウント名/pull-request-practice) にCompare&PullRequest ボタンが表示されず、
プッシュするときに、リモートリポジトリをデフォルトになっている add-myfile を TIadd-myfile などと変更して実行すると Compare&PullRequest ボタンが表示されました。
=> Ti3add myfile

hallogoodbye.txt
=> hallo & goodbye text

kouichi.txt
=> add text.txt

Aichi_and_wakaba.txt
本を見ながら自分用のテキストファイルを追加してみました。
問題がなければ、マージをお願いいたします。
=> add Aichi_and_wakaba.txt

kakisoft.txt
=> add my-file

yamamoto.txt
=> new yamamoto file text

hnk.txt.rtf
=> add wakabachan.txt

neconyan.txt
=> add neconyan.txt

honey-nuts.txt
=> add honey-nuts.txt

nemui_hito.txt
=> add nemui_hito.txt

Maddy1341.txt
自分用のテキストファイルを追加しました
問題なければマージお願いします。
=> Maddy1341.txt

PullRequestText_20170915.txt
練習用のPullRequest用のテキストを追加させて頂きました。
お手数ですが問題がなければマージをよろしくお願いいたします。
=> adding PullRequestText_20170915.txt

0930.txt
=> 私のファイルを追加しました

hitoi1231.rtf
=> 自分用のテキストファイルを作りました！

cielavenir.txt
https://hacktoberfest.digitalocean.com/ 用です
こんな目的に使ってしまいすみませんToT
=> add cielavenir.txt

hello.txt
個人情報を公開したくない方は、本Pull Requestをキャンセルして、ご自身のレポジトリを一度削除お願いします。
その後、
SourceTreeの[設定]アイコン　＞　[高度な設定]タブ　＞　[ユーザー情報]欄の
・名前をニックネームに
=> hello.txtを追加

kenta.txt
I created a text file for me. 
If there is no problem, please do merge.
=> add kenta.txt

takemura1022.txt
=> add takemura1022.txt

xralphack.txt
=> xralphack.txt

Mor8.txt
=> add Mor8.txt

新しくないドキュメント.txt
個人情報を公開したくない方は、本Pull Requestをキャンセルして、ご自身のレポジトリを一度削除お願いします。
その後、
SourceTreeの[設定]アイコン　＞　[高度な設定]タブ　＞　[ユーザー情報]欄の
・名前をニックネームに
=> add testfile

add_my_file_test.txt
=> add_my_file_test_text

yutaro326.txt
テスト用のtxtファイルを追加しました。
マージよろしくお願いいたします。
=> Add myfile

add.txt
=> pull request

.gitignore, add_my_file_test.txt
=> テキストを追加しました

kzzu.txt
個人情報を公開したくない方は、本Pull Requestをキャンセルして、ご自身のレポジトリを一度削除お願いします。
その後、
SourceTreeの[設定]アイコン　＞　[高度な設定]タブ　＞　[ユーザー情報]欄の
・名前をニックネームに
=> add kzzu.txt

zakkan.txt
個人情報を公開したくない方は、本Pull Requestをキャンセルして、ご自身のレポジトリを一度削除お願いします。
その後、
SourceTreeの[設定]アイコン　＞　[高度な設定]タブ　＞　[ユーザー情報]欄の
・名前をニックネームに
=> add zakkan.txt

hogehogehogehoge.txt
=> hogehogehogehogehogehogehogehoge

salesforce-sive2.txt
「わかばちゃんと学ぶ Git使い方入門」の演習で初プルリクエスト。
=> pull-req test

practice-2.md
Testing for pull-request.
please merge if it isn't bad.
=> Markdown-add-test

append-test.txt
=> pull-request-test

dango.txt, wawawawawa.txt
=> Add myfile2

20180206.txt
=> プルリクエストのテスト

ichihana.rtf
=> add ichihana.txt

merge.sh
=> add merge.sh

hogehoge.txt
=> hogehoge.txtの作成

neko-san.txt
neko-san.txtを追加しました♪
猫好きならマージお願いします。
=> neko-san.txtを追加

tanu.txt
=> tanu.txtを新規作成

fuga.txt
=> add fuga.txt

hoge_.txt
=> プルリクエスト練習用

.gitignore, hana.txt, testtesttest3.txt
=> my request for elmas3

ryukam10k.txt
=> add ryukam10k.txt

a.txt
=> add  a.txt

naoppy.txt
自分のテキストファイルを追加
問題なければマージをお願いします
=> add my file

keita777.txt
=> test 20180422

kare.txt
=> add kare.txt

3su3.txt
=> pull-request test for Mac

MitsuS.txt
=> add MitsuS.txt

RaimuKen.txt
=> add RaimuKen.txt

yuimod.txt
=> add file 'yujimod.txt'

0-wakaba-love.txt, wakaba-chan-love.txt
=> Add my love to Wakaba-chan

okkotaro.rtf
=> okkotaro追加

roborobo.txt
=> テスト用に作りました。

20180708_YamKY.txt
...と、Gitでここまで出来るようになってうれしいです！！
=> append Wakabachan.txt  for Practice

20180522_WAK.txt
=> new sample 0522

todo.txt
自分用のテキストファイルを追加してみました．
問題なければマージお願いします．
=> add todo.txt

Tatachiblob.txt
=> Added Tatachiblob.txt

I_love_wakabachan.txt
=> I_love_wakabachan.txt

20180718.txt
練習用のファイルを追加しました。
問題なければ、マージをお願い致します。
=> add pull-request-practice file

pull-request-test_kamoheyo.md
プルリクTest用のファイルを作成しました。
問題なければマージをお願いします。
その後、
・名前をニックネームに
=> プルリクのTest用ファイルを追加

ytestfile.txt
=> add test file

プルプル.txt
=> プルリクエストの練習

ttpractice.txt
add my file
pls merge my request
=> add ttpractice.txt

marusanchi.rtf
=> add marusanchi.txt

whodis.txt
=> Add a new txt file

ステマをしたくなるような本.txt
=> ステマしたくなるような本を追加しました．

!test.txt
=> test_branch_commit

test-san.txt
=> add test-san.txt

Wakaba-chan.txt
=> add Wakaba-chan.txt

めっちゃ新しいドキュメント.txt
=> 自分用のテキストファイルを追加してみました。

miggy_test.txt
=> テキスト追加しました！

kumada.txt
=> kumadaファイル追加

wakabalove.txt
=> add wal\kabalove.txt

201809211428.txt
=> add 201809211428.txt

yamadash.txt
=> 自分用のテキストを追加。

seiyatest.rtf
=> add seiyatest.txt

brazil-legendary.md
=> Added BR info

こんにちは.txt
=> こんにちは.txtを新規作成

新しいテキスト ドキュメント (20).txt
=> add new textfile(20)

78tch.txt
=> add-myfile

新しいテキスト ドキュメント (20)_pull_request_test.txt
=> Hello! This file is for testing pull-request.

sample_pull_request.txt
プルリクエストの作成をしてみました。
マージお願いいたします！！
=> add sample_pull_request.txt

ganariya.txt
=> add ganariya.txt

新しいテキスト ドキュメント (21).txt
=> testtesttestの追加

sei.txt
=> add sei.text

yyy-516, yyyyyyyyy.txt
=> yyyyyyyコミット

iwachoco.txt
pull request
I maked my test file.
If this file isn't wrong, I would like you to merge this.
=> add a test file

新しいテキスト ドキュメントでありたい.txt
=> 湊川先生お疲れ様です

ever.txt
=> everrrrrrrrr

新しいテキスト ドキュメント (24).txt
=> pull-request test

sugarex.txt
=> add sugarex.txt

.gitignore, yadohisa.txt
=> add pull req txt

Takeshikatada.rtf
=> add takeshikatada.rtf

test1203.txt
=> add a file of "test1203.txt "

test20190226y.html
=> テストhtmlを追加しました

20190311.txt
=> Added a new txt file.

.gitignore, minana.txt
=> add minana.txt

cerven12
自分用のテキストファイルを追加してみました
問題なければ、マージお願いします
=> add cerven12.txt

add_text.txt
=> add new text

thanksWakaba.txt
add text file 
湊川先生ありがとうございます！
=> add thanksWakaba.txt

ino1989823.rtf
=> add ino1989823.txt

newFile.txt
自分のファイルを追加したのでプルしてほしいぴょん
よろしくにゃん…
その後、
・名前をニックネームに
=> add newtextfile

add nekosame.txt
=> add nekosame.txt

testfile.txt
=> add sample text file

wakabLalala.txt
=> add wakabLalala.txt

I create a file for studing.txt
=> 自分用ファイルを作成しました。

pull_req_test.txt
練習用のテキストファイルを追加しました 🦍 
問題なければマージをお願いします。
=> add pull_req_test.txt

MyText.rtf
=> add MyText.txt

harada.rtf
=> harada add

joshua.txt
=> eat your live frogs first

hermes.txt
=> Inserted "Hello everyone!".

masaya.txt
=> add masaya.txt

uryy.txt
=> add my account

PRtestfile.txt
=> test commit

令和2_自分用.rtf
=> Add 令和2_自分用

samuraibrass.txt
=> add samuraibrass.txt

hellogit.txt
=> add hellogit.txt

hello.txt
=> add hello.txt

pull_request_test.txt
=> pull_request_test

rakutaro.txt
=> add rakutaro.txt

wa_wa_wa_wakaba.txt
=> add wa_wa_wa_wakaba.txt

ts_gitWakaba.txt
問題がなければマージをお願いします。
その後、
・名前をニックネームに
=> プルリク用テストファイル作成。

namakemono02.rtf
=> 練習用にテキストファイルを追加しました。

ほげほげ.txt
=> add ほげほげ.txt

cielavenir.txt
=> readd cielavenir

20191226.txt
=> added text file

a_aaa_aaa.txt
=> add a_aaa_aaa.txt

pull_test.txt
プルリクエストのテスト用に追加しました。
問題なければマージをお願いします。
=> プルリクエストのテスト用に追加

hirohot.txt
=> add hirohot.txt

hiromaki.txt
=> add hiromaki.txt

mami666.rtf
=> add mami666.rtf

pull request
=> This is a pull request

pull-request-test.js
=> pullリクエスト練習

c110270.txt
=> add c110270.txt

takeuchihiroomi.txt
=> sdd takeuchihiroomi.txt

Shin.html
自分用のファイルを追加してみました。
問題なければ、マージお願いします.
=> add Shin.html

kenken.rtf
自分用のテキストファイルを作ってみました。
問題がなければ、マージお願いします。
=> 自分用のテキストファイルをつくりました

.github/workflows/continuous-integration.yaml
詳細：
https://github.com/marketplace/actions/auto-merge-pull-request
=> Auto-Merge Pull Request 用のyamlを追加

.github/workflows/continuous-integration.yaml
Warning: Unexpected input(s) 'GITHUB_TOKEN', valid inputs are ['token', 'merge-method', 'squash-title', 'do-not-merge-labels', 'required-labels', 'pull-request', 'pull-request-author-associations', 'review-author-associations', 'dry-run']
=> Warningが出ていたのでinputの表記を合わせました

.github/workflows/continuous-integration.yaml
Reverts elmas3/pull-request-practice#2877
=> Revert "トークンの表記を元に戻す"

test001.txt
=> プルリクテストです。お願いします。

ryo.txt
add my textfile.
Please marge.
=> add ryo.txt

tsubu.rtf
=> no message

norihisa1003.txt
=> add norihisa1003.txt

Hyakutake.txt
=> add hyakutake.txt

mukaikatumi.txt
=> ファイルを新規追加（向井克己）

hogehoge.txt, wata5f68.txt
=> add hogehoge
